import {fileURLToPath} from 'node:url';
import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const wb=Workbook.create();
const s=wb.worksheets.add('體驗課報名');
s.getRange('A1:Y1').values=[["報名時間","報名編號","小朋友名字","年級","學校","體驗課程","偏好時段","相關經驗","經驗補充","家長稱呼","家長手機","家長Email","其他安排需求","個資使用同意","同意條款版本","報名來源","聯絡進度","LINE已聯絡","確認信狀態","寄信時間","寄信錯誤","請求識別碼","資料指紋","寄信嘗試次數","最後嘗試時間"]];
s.getRange('A1:Y12').format.font={name:'Arial',size:11};
s.getRange('A1:Y1').format.fill='#eef0f3';
s.getRange('A1:Y1').format.font.bold=true;
s.getRange('A1:Y1').format.rowHeightPx=42;
s.getRange('A1:Y12').format.columnWidthPx=150;
s.getRange('A1:Y1').format.wrapText=true;
s.getRange('F1:G12').format.columnWidthPx=230;
s.getRange('L1:L12').format.columnWidthPx=250;
s.getRange('C2:P1000').setNumberFormat('@');
s.freezePanes.freezeRows(1);
s.showGridLines=true;
wb.recalculate();
const png=await wb.render({sheetName:'體驗課報名',range:'A1:H5',scale:1,format:'png'});
await fs.writeFile(new URL('./sheet-preview.png',import.meta.url),new Uint8Array(await png.arrayBuffer()));
const out=await SpreadsheetFile.exportXlsx(wb);
await out.save(fileURLToPath(new URL('./體驗課報名管理表.xlsx',import.meta.url)));
console.log('Workbook ready');